name: Webmentions Sync

concurrency:
  group: webmention_sync
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

  # IFTT webhook
  repository_dispatch:
    types:
      - webmention_webhook

jobs:
  webmentions-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: dev
          token: ${{ secrets.GH_PAGES_ACCESS_TOKEN }}
      - name: Sync webmentions
        env:
          WEBMENTIONS_IO_TOKEN: ${{ secrets.WEBMENTIONS_IO_TOKEN }}
        run: node ./webmentions/sync.js
      - name: Commit to repository
        env:
          COMMIT_MSG: |
            Sync webmentions
        run: |
          git config user.email "jan.monschke@gmail.com"
          git config user.name "Jan Monschke"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin dev)
